spring:
  datasource:
    url: jdbc:mysql://localhost:3306/permission?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  session:
    store-type: redis
  redis:
#    host: 192.168.16.221
    #    port: 6403
    host: 192.168.74.128
    port: 6379
    password:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false  # 开发阶段务必关闭缓存 (=false)

## Dubbo
dubbo:
  application:
    name: user-center-provider
  registry:
    protocol: zookeeper
    address: 192.168.74.128:2181,192.168.74.129:2181,192.168.74.130:2181,192.168.74.131:2181
#    address: localhost:2181
  protocol: #通信规则（通信协议和接口）
    name: dubbo
    port: 20888
  version: 1.0.0
