server:
  port: 18081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driverClassName:  com.mysql.cj.jdbc.Driver
    platform: mysql

## mybatis-plus 详情 ---> https://www.jianshu.com/p/700f8ffc6074
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
    #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.qooence.code.usercenter.entity
#  typeEnumsPackage: com.baomidou.springboot.db.entity.enums 通用枚举
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      #logic-delete-value: Y
      #logic-not-delete-value: N
      db-type: mysql
    refresh: true
    #sql-injector: com.baomidou.mybatisplus.extension.injector.LogicSqlInjector
      #自定义填充策略接口实现
      #meta-object-handler: com.baomidou.springboot.xxx
      #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    # map-underscore-to-camel-case: true # 数据库字段与数据对象字段的映射策略
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印sql

# JWT
jwt:
  header: Authorization
  secret: mySecret
  #token有效期一天
  expiration: 86400
  tokenHead: "Bearer "

## Dubbo
dubbo:
  application:
    name: user-center-provider
  registry:
    protocol: zookeeper
    address: 192.168.74.128:2181,192.168.74.129:2181,192.168.74.130:2181,192.168.74.131:2181
#    address: localhost:2181
  protocol: #通信规则（通信协议和接口）
    name: dubbo
    port: 20888
  version: 1.0.0
